@api = http://localhost:3000/auth

### signup
POST {{api}}/signup
Content-Type: application/json

{
  "email": "joe@faztweb.com",
  "password": "joepassword"
}

### signin 
POST {{api}}/signin
Content-Type: application/json

{
  "email": "joe@faztweb.com",
  "password": "joepassword"
}

### refresh token
POST {{api}}/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzYxMzEwMzgsImV4cCI6MTYzNjEzMTA2OCwiYXVkIjoiNjE4NTUzYmY1NzM1MmMwYmQzMjU5YWM5IiwiaXNzIjoiZmF6dC5kZXYifQ.tAGWSqvSKMhhpQOOrzDpARdFxglTxs6L9TmGZreytp4"
}

### logout
DELETE {{api}}/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzYxMzE4MjcsImV4cCI6MTYzNjEzMTg1NywiYXVkIjoiNjE4NTUzYmY1NzM1MmMwYmQzMjU5YWM5IiwiaXNzIjoiZmF6dC5kZXYifQ.hzWki3YUSIMNf3c6_P-PA9-2g3I15urRcDL2mX0yM8o"
}