@api = http://localhost:3000/auth

### signup
POST {{api}}/signup
Content-Type: application/json

{
  "email": "joe1210@faztweb.com",
  "password": "joepassword"
}

### signin 
POST {{api}}/signin
Content-Type: application/json

{
  "email": "joe@faztweb.com",
  "password": "joepassword"
}

### refresh token
POST {{api}}/refresh-token

### logout
POST {{api}}/logout