@api = http://localhost:3000/auth

### signup
POST {{api}}/signup
Content-Type: application/json

{
  "email": "fazttech14@gmail.com",
  "password": "fazttech123"
}

### signin 
POST {{api}}/signin
Content-Type: application/json

{
  "email": "fazttech14@gmail.com",
  "password": "fazttech123"
}

### refresh token
POST {{api}}/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDYwOTkxNjUsImV4cCI6MTY0NjA5OTE5NSwiYXVkIjoiNjIxZDcwMGViNWZmZTk5ZjcxMDM4NDAwIiwiaXNzIjoiZmF6dC5kZXYifQ.Bpz79I6NFEVjCLpkkd2lfFc8oEKdv0dZXcVMg_YW6C8"
}

### logout
DELETE {{api}}/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzYxMzE4MjcsImV4cCI6MTYzNjEzMTg1NywiYXVkIjoiNjE4NTUzYmY1NzM1MmMwYmQzMjU5YWM5IiwiaXNzIjoiZmF6dC5kZXYifQ.hzWki3YUSIMNf3c6_P-PA9-2g3I15urRcDL2mX0yM8o"
}

### profile
GET {{api}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NzkwMDUyOTIsImV4cCI6MTcxMDU2Mjg5MiwiYXVkIjoiNjQxMzk0ZGYxZTQ1YzA2YTFjMTgwZjA1IiwiaXNzIjoiZmF6dC5kZXYifQ.9pmzDvElMjsEnttBPrKtkk4TWIolT8L-QuNWR4uE5UE