
### 
GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzU5NTM4OTksImV4cCI6MTYzNTk1MzkxOSwiYXVkIjoiNjE4MWI3YzU0N2I0YjY1ZDkyOTc4NzgwIiwiaXNzIjoiZmF6dC5kZXYifQ.F21RFgWXgEL2mdUfAe02Ye800rP082lB17Hcwrsr_fc

### 404 Error
GET http://localhost:3000/notfound